# Generated by Django 4.2.16 on 2024-10-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('maplink', models.URLField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
